package pixelart.core;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import org.mockito.Mockito;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.doReturn;
import static org.mockito.Mockito.doThrow;


/*public class ReadJsonTest {

    private Grid grid;
    private GridStateHandler gridStateHandler; 
    private int gridSize;

    @BeforeEach
    public void setup() {
        int gridSize = 5;
        int pixelSize = 10;
        this.grid = new Grid(gridSize,pixelSize);
        this.gridStateHandler = new GridStateHandler();
    }

    @AfterEach
    public void tearDown() {
        File file = new File("testJsonCanvas.json");
        if (file.exists()) {
            file.delete();
        }
    }

    @Test
    public void successfullyReadJson() {
        String filepathJson = "jsonCanvas.json";
        try {
            String content = gridStateHandler.readJsonFile(filepathJson); 
            assertNotNull(content);
        } catch (IOException e) {
            System.out.println("Error retrieving file");
        }
    }

    @Test
    public void testReadJsonFileFileNotFound() {
        String invalidFilepath = "invalidFilePath.json";
        assertThrows(IOException.class, () -> {
            gridStateHandler.readJsonFile(invalidFilepath); 
        }, "The file is nonexistent");
    }

    @Test //This test was generated by AI. Based on the previous test, AI updatet it to accord to the refactor. 
    public void testLoadJsonFileWithValidFileName() throws IOException {
        String validJsonContent = "{ \"canvas\": [[\"B\", \"W\", \"B\", \"W\", \"B\"], [\"W\", \"B\", \"W\", \"B\", \"W\"], [\"B\", \"W\", \"B\", \"W\", \"B\"], [\"W\", \"B\", \"W\", \"B\", \"W\"], [\"B\", \"W\", \"B\", \"W\", \"B\"]]}";
        GridStateHandler gridStateHandler = Mockito.spy(new GridStateHandler());
        doReturn(validJsonContent).when(gridStateHandler).readJsonFile(anyString());
        gridStateHandler.loadState();
        for (int row = 0; row < gridSize; row++) {
            for (int col = 0; col < gridSize; col++) {
                String expectedColor = (row + col) % 2 == 0 ? "B" : "W";
                assertEquals(expectedColor, grid.getPixel(row, col).toString()); 
            }
        }
    }


    @Test
    public void testLoadJsonFileOnEmptyFile() throws IOException {
        String emptyTestFile = "testEmptyFileName.json";
        GridStateHandler gridSpy = new GridStateHandler();

        File file = new File(emptyTestFile);
        file.createNewFile(); 
        gridStateHandler.loadState();

        for (int row = 0; row < gridSize; row++ ) {
            for (int col = 0; col < gridSize; col++ ) {
                String expectedColor = "W";
                String actualColor = grid.getPixel(row, col).getColorAsString();  //<-- WRONG!
                assertEquals(expectedColor, actualColor);
            }
        }
        file.delete();
    }

    @Test
    public void testLoadJsonFileOnInvalidFile() throws IOException {
        String invalidFilepath = "invalidFilePath.json";
        GridStateHandler gridSpy = Mockito.spy(gridStateHandler);
        doThrow(new FileNotFoundException(invalidFilepath)).when(gridSpy).readJsonFile(anyString());
        gridSpy.loadState();
        doThrow(new IOException()).when(gridSpy).readJsonFile(anyString());
        gridSpy.loadState();
    }
} */
