package pixelart.ui;

import java.io.IOException;

import javafx.fxml.FXML;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import pixelart.core.Grid;
import pixelart.core.GridStateHandler;

/**
 * AppController is the main controller class for our JavaFX application.
 * It controls the interaction between the user and our canvas.
 * The user is able to draw and erase on the different pixels.
 * This is done by using left and right mouse click.
 */
public class AppController {

    /**
     * The main grid containing the canvas element.
     */
    @FXML
    private GridPane gridPane;

    /**
     * The color palette displayed as a set of color buttons.
     */
    @FXML
    private HBox colorPalette;

    /**
     * The grid model containing our pixeldata.
     */
    private Grid grid;

    /**
     * Managed saving and loading gridstate from server.
     */
    private GridStateHandler gridStateHandler;

    /** Manages color selection and palette operations. */
    private ColorController colorController;

    /**
     * Controls the grid’s visual and interactive behavior.
     */
    private GridController gridController;

    /**
     * Initializes the controller as well as the canvas
     * Tries to retrieve canvas from server. Else a new one.
     *
     * @throws IOException if there´s an error initializing
     * @throws InterruptedException if the loading from server process fails
     */
    @FXML
    public void initialize() throws IOException, InterruptedException {
        this.colorController = new ColorController(colorPalette);
        colorController.initializeColorPalette();

        try {
            this.gridStateHandler = new GridStateHandler();
            String[][] theCurrentState = gridStateHandler.loadCanvas();
            grid = new Grid(theCurrentState, GridController.PIXEL_SIZE);
        } catch (IOException e) {
            this.grid = new Grid(
                    GridController.GRID_SIZE_HEIGHT,
                    GridController.GRID_SIZE_WIDTH,
                    GridController.PIXEL_SIZE);
        } catch (InterruptedException e) {
            System.out.println("InterruptedException");
            this.grid = new Grid(
                    GridController.GRID_SIZE_HEIGHT,
                    GridController.GRID_SIZE_WIDTH,
                    GridController.PIXEL_SIZE);
        } catch (Exception e) {
            e.printStackTrace();
            this.grid = new Grid(
                    GridController.GRID_SIZE_HEIGHT,
                    GridController.GRID_SIZE_WIDTH,
                    GridController.PIXEL_SIZE);
        }

        this.gridController =
        new GridController(grid, gridPane, gridStateHandler);
        gridController.initializeGridPane();

        //This code was generated by Claude to ensure correct color
        //in the handler used in ColorController from here:
        colorController.setOnColorSelected(
        color -> gridController.setCurrentColor(color));
        //To here.
    }

    /**
     * Retrieves the controller responsible for managing grid operations.
     *
     * @return the GridController instance managing the grid's behavior.
     */
    @edu.umd.cs.findbugs.annotations.SuppressFBWarnings("EI_EXPOSE_REP")
    public GridController getGridController() {
        return gridController;
    }
}
